language: python 

python: 
  - 3.5

before_script: 
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
script: 
  - nosetests --with-coverage 
after_success: 
  - coveralls
